# Desafío - Introducción al ambiente de trabajo

# Desafío 1: Hola Mundo

In [2]:
print("Hola Mundo, esta es mi primera incursión en Python")

Hola Mundo, esta es mi primera incursión en Python

# Desafío 2: Ingreso de variables

In [3]:
Nombre = "Francisco"
Edad = 31
Lista = ["Videojuegos", "Padel", "Comer"]
Mascota = True

serie = {
    "Nombre":"Francisco",
    "Edad":31,
    "Lista":["Videojuegos", "Padel", "Comer"],
    "Mascota":True
}

print(serie)

{'Nombre': 'Francisco', 'Edad': 31, 'Lista': ['Videojuegos', 'Padel', 'Comer'], 'Mascota': True}

# Desafío 3: Imprimiendo Variables

In [4]:
print(Nombre)
print(Edad)
print(Lista[1])
print(Mascota)

Francisco
31
Padel
True

In [5]:
print("La variable Nombre es del tipo: "+str(type(Nombre)))
print("La variable Edad es del tipo: "+str(type(Edad)))
print("La variable Lista es del tipo: "+str(type(Lista)))
print("La variable Mascota es del tipo: "+str(type(Mascota)))

La variable Nombre es del tipo: <class 'str'>
La variable Edad es del tipo: <class 'int'>
La variable Lista es del tipo: <class 'list'>
La variable Mascota es del tipo: <class 'bool'>

In [6]:
print(f"¡Hola!, mi nombre es {Nombre} y tengo {Edad} años de edad, \nmis 3 actividades favoritas son: {Lista[0]}, {Lista[1]} y {Lista[2]},\nsi me preguntan si tengo mascota la verdad es que {Mascota}, y su nombre es Docky")

¡Hola!, mi nombre es Francisco y tengo 31 años de edad,
mis 3 actividades favoritas son: Videojuegos, Padel y Comer,
si me preguntan si tengo mascota la verdad es que True, y su nombre es Docky

# Desafío 4

# 1) print('Estaba la pájara pinta sentada en el verde limón)

In [7]:
"Comentario: Arroja error porque falta finalizar la cadena de texto dentro del print, es decir, falta la '' \' '' del final"

"Comentario: Arroja error porque falta finalizar la cadena de texto dentro del print, es decir, falta la '' ' '' del final"

# 2) print('Mi nombre es' name 'y tengo' edad, 'años')

In [8]:
"Comentario: Arroja error porque falta agregar un \"+\" a cada lado de las variables \"name\" y \"edad\", también hay una \",\" demás después de \"edad\""

'Comentario: Arroja error porque falta agregar un "+" a cada lado de las variables "name" y "edad", también hay una "," demás después de "edad"'

# 3) import padnas as pd
#    import nunnpy as np

In [ ]:
"Comentario: Arroja error porque tanto pandas como numpy están mal escritos, python no conoce dichas librerías tal cual cómo están escritas"

'Comentario: Arroja error porque tanto pandas como numpy están mal escritos, python no conoce dichas librerías tal cual cómo están escritas'

# 4) "Ornitorrinco" + 45

In [ ]:
"Comentario: Arroja error porque python no es capaz de sumar un string con un int"

'Comentario: Arroja error porque python no es capaz de sumar un string con un int'

# Desafío 5: Utilizando pandas y numpy

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("flights.csv")

print(df.head())

   year     month  passengers
0  1949   January         112
1  1949  February         118
2  1949     March         132
3  1949     April         129
4  1949       May         121

In [ ]:
print(df.tail())

     year      month  passengers
139  1960     August         606
140  1960  September         508
141  1960    October         461
142  1960   November         390
143  1960   December         432

In [ ]:
df.year.describe()

count     144.000000
mean     1954.500000
std         3.464102
min      1949.000000
25%      1951.750000
50%      1954.500000
75%      1957.250000
max      1960.000000
Name: year, dtype: float64

In [ ]:
df.year.value_counts()

1949    12
1950    12
1951    12
1952    12
1953    12
1954    12
1955    12
1956    12
1957    12
1958    12
1959    12
1960    12
Name: year, dtype: int64

In [ ]:
df.month.value_counts()

August       12
October      12
April        12
November     12
June         12
July         12
December     12
September    12
May          12
February     12
January      12
March        12
Name: month, dtype: int64

In [ ]:
variable_a = df.head(15)
variable_b = df.tail(15)
variable_c = variable_a.append(variable_b)

In [ ]:
variable_c

     year      month  passengers
0    1949    January         112
1    1949   February         118
2    1949      March         132
3    1949      April         129
4    1949        May         121
5    1949       June         135
6    1949       July         148
7    1949     August         148
8    1949  September         136
9    1949    October         119
10   1949   November         104
11   1949   December         118
12   1950    January         115
13   1950   February         126
14   1950      March         141
129  1959    October         407
130  1959   November         362
131  1959   December         405
132  1960    January         417
133  1960   February         391
134  1960      March         419
135  1960      April         461
136  1960        May         472
137  1960       June         535
138  1960       July         622
139  1960     August         606
140  1960  September         508
141  1960    October         461
142  1960   November         390
143  1960   December         432

In [1]:
#Datos de passengers
print(f"La media de la columna passengers es {np.mean(df.passengers)}")
print(f"La mediana de la columna passengers es {np.median(df.passengers)}")
print(f"La desviación estándar de la columna passengers es {np.std(df.passengers)}")
print()

#Datos de variable_c
print(f"La media de las últimas y primeras 15 observaciones es {np.mean(variable_c.passengers)}")
print(f"La mediana de las últimas y primeras 15 observaciones es {np.median(variable_c.passengers)}")
print(f"La desviación estándar de las últimas y primeras 15 observaciones es {np.std(variable_c.passengers)}")

print("""
Comentario: La cantidad de pasajeros ha aumetado durante el pasar del tiempo, y si se toman los extremos (primeros y últimos 15 meses),
es de esperar que la media aumente, la mediana curiosamente disminuya y que la desviación estándar sea más grande que tomando passengers completo
""")

import matplotlib.pyplot as plt
df.groupby(by = "year")['passengers'].plot()
plt.xlabel("Número de mes desde el inicio hasta el mes 143")
plt.ylabel("Cantidad de pasajeros")
plt.title("Evolución de los últimos 143 meses de datos (color por año)")
plt.show()

print("También se nota claramente una ciclicidad en la cantidad de pasajeros, va pasando por temporadas altas y bajas :) ")

NameError: ignored